# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 01:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='login',
            fields=[
                ('login_ID', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=50)),
                ('password', models.CharField(max_length=50)),
                ('user_id', models.IntegerField(max_length=32, null=True)),
                ('token', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'login',
            },
        ),
        migrations.CreateModel(
            name='order',
            fields=[
                ('kuaidi_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('kehu_name', models.CharField(max_length=255, null=True)),
                ('get_back', models.CharField(max_length=255, null=True)),
                ('box_num', models.CharField(max_length=32, null=True)),
                ('phone', models.CharField(max_length=11, null=True)),
                ('image', models.CharField(max_length=255, null=True)),
                ('get_time', models.DateTimeField(null=True)),
                ('give_monhey', models.CharField(max_length=255, null=True)),
                ('user_id', models.IntegerField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'older',
            },
        ),
        migrations.CreateModel(
            name='user_info',
            fields=[
                ('user_id', models.AutoField(max_length=32, primary_key=True, serialize=False)),
                ('truename', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=50)),
                ('carnumber', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=11)),
                ('id_card', models.CharField(max_length=50)),
                ('carteam', models.CharField(max_length=50, null=True)),
            ],
            options={
                'db_table': 'user_info',
            },
        ),
        migrations.CreateModel(
            name='version',
            fields=[
                ('versionid', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('version', models.CharField(default=0, max_length=10)),
                ('url', models.CharField(max_length=255, null=True)),
            ],
            options={
                'db_table': 'version',
            },
        ),
    ]
