# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 01:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='order_num',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
