# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 01:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_order_order_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='head_img',
            field=models.FileField(null=True, upload_to='./uploadhead'),
        ),
    ]
