# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 02:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_order_head_img'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_info',
            name='carteam',
        ),
        migrations.AddField(
            model_name='user_info',
            name='car_id',
            field=models.FileField(null=True, upload_to='./uploadcar'),
        ),
        migrations.AddField(
            model_name='user_info',
            name='driver_id',
            field=models.FileField(null=True, upload_to='./uploaddriver'),
        ),
        migrations.AlterField(
            model_name='user_info',
            name='id_card',
            field=models.FileField(null=True, upload_to='./uploadperson'),
        ),
    ]
