# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-06 02:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_auto_20171106_0223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='head_img',
        ),
        migrations.AddField(
            model_name='order',
            name='take_user_id',
            field=models.IntegerField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='user_info',
            name='name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
