# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 07:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_login_headimg'),
    ]

    operations = [
        migrations.CreateModel(
            name='voyage',
            fields=[
                ('voyage_id', models.AutoField(default=0, primary_key=True, serialize=False)),
                ('voyage_num', models.CharField(max_length=255, null=True)),
                ('voyage_models', models.CharField(max_length=255, null=True)),
                ('get_box_address', models.CharField(max_length=255, null=True)),
                ('in_return_box', models.CharField(max_length=255, null=True)),
                ('take_user_id', models.IntegerField(max_length=32, null=True)),
            ],
            options={
                'db_table': 'voyage',
            },
        ),
        migrations.RenameField(
            model_name='order',
            old_name='box_num',
            new_name='getorder_num',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='get_back',
            new_name='kuaidi_num',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='give_monhey',
            new_name='make_box_time',
        ),
        migrations.RenameField(
            model_name='order',
            old_name='image',
            new_name='person',
        ),
        migrations.RemoveField(
            model_name='order',
            name='get_time',
        ),
        migrations.RemoveField(
            model_name='order',
            name='kehu_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='user_id',
        ),
        migrations.AddField(
            model_name='order',
            name='number',
            field=models.FloatField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='v',
            field=models.FloatField(max_length=32, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='voyage_id',
            field=models.IntegerField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='weight',
            field=models.FloatField(max_length=255, null=True),
        ),
    ]
