# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 07:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_auto_20171113_0703'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='make_box_address',
            field=models.CharField(max_length=255, null=True),
        ),
    ]
