# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-13 07:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_order_make_box_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='type',
            field=models.IntegerField(default=0, max_length=1),
        ),
    ]
