# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-16 02:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_order_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='voyage',
            name='imgname',
            field=models.FileField(null=True, upload_to='./equipment'),
        ),
    ]
